export const data = {
  Result: {
    openTasks: 2,
    completedTasks: 5,
    Data: [
      {
        taskTitle: 'Appointment Screen with testing',
        assignee: 'Ali Sultan',
        dateAssigned: '12-02-2024',
        dueDate: '14-02-2024',
        storyPoint: 16,
        status: 'Pending',
        description:
          'Implement the appointment screen and write unit tests for it.',
        assignedBy: 'Project Manager',
        priority: 'High',
      },
      {
        taskTitle: 'User Authentication System',
        assignee: 'Sara Khan',
        dateAssigned: '10-02-2024',
        dueDate: '13-02-2024',
        storyPoint: 12,
        status: 'In Progress',
        description:
          'Develop the login and registration system with token-based authentication.',
        assignedBy: 'Lead Developer',
        priority: 'High',
      },
      {
        taskTitle: 'API Integration for Payments',
        assignee: 'Mohammad Aziz',
        dateAssigned: '11-02-2024',
        dueDate: '15-02-2024',
        storyPoint: 18,
        status: 'Pending',
        description:
          'Integrate Stripe payment gateway and test various payment scenarios.',
        assignedBy: 'Project Manager',
        priority: 'Medium',
      },
      {
        taskTitle: 'Dashboard UI Design',
        assignee: 'Fatima Noor',
        dateAssigned: '09-02-2024',
        dueDate: '12-02-2024',
        storyPoint: 10,
        status: 'Completed',
        description: 'Design the user interface for the admin dashboard.',
        assignedBy: 'UI/UX Lead',
        priority: 'Low',
      },
      {
        taskTitle: 'Bug Fix: Order Processing Delay',
        assignee: 'Zain Ahmed',
        dateAssigned: '12-02-2024',
        dueDate: '14-02-2024',
        storyPoint: 8,
        status: 'In Progress',
        description:
          'Resolve the issue causing a delay in order processing after submission.',
        assignedBy: 'QA Lead',
        priority: 'High',
      },
      {
        taskTitle: 'Backend API for User Profile Management',
        assignee: 'Ayesha Khan',
        dateAssigned: '10-02-2024',
        dueDate: '13-02-2024',
        storyPoint: 14,
        status: 'Pending',
        description:
          'Develop backend services to manage user profile creation and updates.',
        assignedBy: 'Backend Lead',
        priority: 'Medium',
      },
      {
        taskTitle: 'Notification System Setup',
        assignee: 'Umar Farooq',
        dateAssigned: '09-02-2024',
        dueDate: '11-02-2024',
        storyPoint: 20,
        status: 'Completed',
        description:
          'Implement an email and push notification system for important events.',
        assignedBy: 'DevOps Lead',
        priority: 'Low',
      },
    ],
  },
};
