// login
export const LOGIN_USER = 'LOGIN_USER';
export const SET_USER_ROLE = 'SET_USER_ROLE';
export const SAVE_USER_DATA_AND_ROLE = 'SAVE_USER_DATA_AND_ROLE';
export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA';
// signup
export const SIGNUP_USER_START = 'SIGNUP_USER_START';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';
// punch in/out timer
export const SAVE_PUNCH_IN_TIME = 'SAVE_PUNCH_IN_TIME';
export const SAVE_PUNCH_OUT_TIME = 'SAVE_PUNCH_OUT_TIME';
export const SAVE_TIMER = 'SAVE_TIMER';
export const SAVE_LOCATION = 'SAVE_LOCATION';
export const SAVE_PUNCH_IN_LOCATION = 'SAVE_PUNCH_IN_LOCATION';
export const SAVE_PUNCH_OUT_LOCATION = 'SAVE_PUNCH_OUT_LOCATION';
// language
export const SET_LANGUAGE = 'SET_LANGUAGE';
// leaves
export const FETCH_LEAVES_START = 'FETCH_LEAVES_START';
export const FETCH_LEAVES_SUCCESS = 'FETCH_LEAVES_SUCCESS';
export const FETCH_LEAVES_FAILURE = 'FETCH_LEAVES_FAILURE';
export const CLEAR_LEAVES_STATE = 'CLEAR_LEAVES_STATE';
export const POST_LEAVE_START = 'POST_LEAVE_START';
export const POST_LEAVE_SUCCESS = 'POST_LEAVE_SUCCESS';
export const POST_LEAVE_FAILURE = 'POST_LEAVE_FAILURE';
export const UPDATE_LEAVE_STATUS_START = 'UPDATE_LEAVE_STATUS_START';
export const UPDATE_LEAVE_STATUS_SUCCESS = 'UPDATE_LEAVE_STATUS_SUCCESS';
export const UPDATE_LEAVE_STATUS_FAILURE = 'UPDATE_LEAVE_STATUS_FAILURE';
export const PATCH_LEAVE_STATUS_START = 'PATCH_LEAVE_STATUS_START';
export const PATCH_LEAVE_STATUS_SUCCESS = 'PATCH_LEAVE_STATUS_SUCCESS';
export const PATCH_LEAVE_STATUS_FAILURE = 'PATCH_LEAVE_STATUS_FAILURE';
// tasks
export const FETCH_TASKS_START = 'FETCH_TASKS_START';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';
export const CLEAR_TASKS_STATE = 'CLEAR_TASKS_STATE';
export const POST_TASK_START = 'POST_TASK_START';
export const POST_TASK_SUCCESS = 'POST_TASK_SUCCESS';
export const POST_TASK_FAILURE = 'POST_TASK_FAILURE';
export const PATCH_TASK_STATUS_START = 'PATCH_TASK_STATUS_START';
export const PATCH_TASK_STATUS_SUCCESS = 'PATCH_TASK_STATUS_SUCCESS';
export const PATCH_TASK_STATUS_FAILURE = 'PATCH_TASK_STATUS_FAILURE';
// dashboard
export const FETCH_DASHBOARD_COUNT_START = 'FETCH_DASHBOARD_COUNT_START';
export const FETCH_DASHBOARD_COUNT_SUCCESS = 'FETCH_DASHBOARD_COUNT_SUCCESS';
export const FETCH_DASHBOARD_COUNT_FAILURE = 'FETCH_DASHBOARD_COUNT_FAILURE';
export const CLEAR_DASHBOARD_COUNT_STATE = 'CLEAR_DASHBOARD_COUNT_STATE';
// change password
export const CHANGE_PASSWORD_START = 'CHANGE_PASSWORD_START';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';
// profile
export const FETCH_PROFILE_START = 'FETCH_PROFILE_START';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE';
export const CLEAR_PROFILE_STATE = 'CLEAR_PROFILE_STATE';
