export const LOGIN_USER = 'LOGIN_USER';
export const SET_USER_ROLE = 'SET_USER_ROLE';
export const SAVE_USER_DATA_AND_ROLE = 'SAVE_USER_DATA_AND_ROLE';
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA';
export const SAVE_PUNCH_IN_TIME = 'SAVE_PUNCH_IN_TIME';
export const SAVE_PUNCH_OUT_TIME = 'SAVE_PUNCH_OUT_TIME';
export const SAVE_TIMER = 'SAVE_TIMER';
export const SET_LANGUAGE = 'SET_LANGUAGE';
